services:
  - type: web
    name: checkins-distribution
    env: static
    buildCommand: npm ci && npm run build
    staticPublishPath: ./dist/chicken-distribution/browser
    routes:
      - type: rewrite
        source: /*
        destination: /index.html
